### ISSUE TITLE
opencv-code.com malware

### ISSUE THREAD

**Issue by notfed** [alyssaq/opencv#7]
Remove the links to opencv-code.com; it now leads to a malware site.

**Comment by alyssaq** [comment]
Updated to link the actual code on github.
Thanks

**Comment by notfed** [comment]
I found the original article on WayBack machine: https://web.archive.org/web/20160316131624/http://opencv-code.com/tutorials/automatic-perspective-correction-for-quadrilateral-objects/

**Comment by alyssaq** [comment]
Nice find! I added links to those archives
